services:
  - type: web
    name: trackio-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run dev
    plan: free
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: trackio-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run dev
    plan: free
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: TelexPH-db
    plan: free
