services:
  - type: web
    name: trackio-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node src/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://hernanidev:telexph102271080030@telexph.6fknsyx.mongodb.net/trackio?retryWrites=true&w=majority&appName=TelexPH&tls=true
      - key: JWT_SECRET
        value: yourSuperSecretKey

  - type: web
    name: trackio-frontend
    env: node
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://trackio-backend.onrender.com
