import React from "react";

const formatDate = (date) => {
  if (!date) return "N/A";
  return new Date(date).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
};

const Box = ({ title, children }) => (
  <div style={{ marginBottom: 14, pageBreakInside: "avoid" }}>
    <div
      style={{
        fontWeight: 700,
        fontSize: 12,
        marginBottom: 10,
      }}
    >
      {title}
    </div>
    <div
      style={{
        padding: "8px",
        border: "1px solid #e5e7eb",
        borderRadius: 4,
        background: "#ffffff",
        whiteSpace: "pre-wrap",
        fontSize: 11,
        lineHeight: 1.45,
      }}
    >
      {children}
    </div>
  </div>
);

const InfoTable = ({ rows }) => {
  const gridRows = [];
  for (let i = 0; i < rows.length; i += 2) {
    gridRows.push(rows.slice(i, i + 2));
  }

  return (
    <table
      style={{
        width: "100%",
        borderCollapse: "collapse",
        marginBottom: 12,
        fontSize: 11,
      }}
    >
      <tbody>
        {gridRows.map((pair, rowIndex) => (
          <tr key={rowIndex}>
            {pair.map(([label, value], colIndex) => (
              <React.Fragment key={colIndex}>
                <td
                  style={{
                    width: "18%",
                    padding: "5px 6px",
                    fontWeight: 600,
                    border: "1px solid #e5e7eb",
                    background: "#f9fafb",
                    verticalAlign: "top",
                    whiteSpace: "nowrap",
                  }}
                >
                  {label}
                </td>
                <td
                  style={{
                    width: "32%",
                    padding: "5px 6px",
                    border: "1px solid #e5e7eb",
                    verticalAlign: "top",
                  }}
                >
                  {value || "N/A"}
                </td>
              </React.Fragment>
            ))}

            {/* Fill empty cells if odd number of rows */}
            {pair.length === 1 && (
              <>
                <td style={{ border: "1px solid #e5e7eb" }} />
                <td style={{ border: "1px solid #e5e7eb" }} />
              </>
            )}
          </tr>
        ))}
      </tbody>
    </table>
  );
};

const ExportCoachingPDF = React.forwardRef(({ formData }, ref) => {
  return (
    <div
      ref={ref}
      id="coaching-pdf-export"
      style={{
        position: "fixed",
        top: "-10000px",
        left: 0,
        width: 600,
        padding: 14,
        background: "#fff",
        color: "#000",
        fontFamily: "Arial, sans-serif",
        fontSize: 12,
        lineHeight: 1.35,
        boxSizing: "border-box",
      }}
    >
      {/* HEADER */}
      <table style={{ width: "100%", marginBottom: 14 }}>
        <tbody>
          <tr>
            <td style={{ verticalAlign: "top" }}>
              <div style={{ fontWeight: 700, fontSize: 14 }}>
                TELEX BUSINESS SUPPORT SERVICES INC.
              </div>
              <div style={{ fontSize: 11, marginTop: 2 }}>
                Telex Building, Brgy. Cawayan Bugtong
                <br />
                Guimba, Nueva Ecija 3115
                <br />
                044-950-4196
              </div>
            </td>
            <td style={{ textAlign: "right", verticalAlign: "top" }}>
              <img
                src={`${window.location.origin}/telex-logo.png`}
                alt="TELEX Logo"
                style={{ height: 44 }}
              />
            </td>
          </tr>
        </tbody>
      </table>

      <hr
        style={{
          border: "none",
          borderTop: "1px solid #e5e7eb",
          marginTop: 18,
        }}
      />

      {/* BASIC INFO */}
      <InfoTable
        rows={[
          ["Agent Name", formData.agentName],
          ["Coach / Supervisor", formData.coachName],
          ["Team Leader", formData.teamLeaderName],
          ["Date of Mistake", formatDate(formData.dateOfMistake)],
          ["Coaching Date", formatDate(formData.coachingDate)],
        ]}
      />

      <Box title="Coaching Mistake">
        {formData.coachingMistake || "No mistake"}
      </Box>

      <Box title="Agent Explanation">
        {formData.respondantExplanation || "No explanation"}
      </Box>

      <Box title="Action Plan">{formData.actionPlan || "No action plan"}</Box>

      {/* FOOTER */}
      <div
        style={{
          marginTop: 12,
          paddingTop: 6,
          borderTop: "1px solid #d1d5db",
          fontSize: 10,
          textAlign: "center",
          color: "#555",
        }}
      >
        Generated by Telex HR System • {new Date().toLocaleString()}
      </div>
    </div>
  );
});

export default ExportCoachingPDF;
